name: Create Git Tag from RELEASE file

permissions:
  contents: write

on:
  push:
    paths:
      - 'RELEASE' # only run when RELEASE file changes

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read version from RELEASE file
      id: read_release
      run: |
        VERSION=$(cat RELEASE | tr -d '[:space:]')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "Version read: $VERSION"

    - name: Create Git tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git tag $VERSION
        git push origin $VERSION
      env:
        VERSION: ${{ env.VERSION }}