name: Publish Release

permissions:
  contents: write
  discussions: write
  id-token: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Perform Publishing
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.11
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: "3.11"

      - name: Bundle
        shell: bash
        run: |
          echo ${{ github.sha }} > release.txt
          bash zbundle.sh
          tar -czf theia-dcnf-ide.tar.gz -C .dist .
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            release.txt
            theia-dcnf-ide.tar.gz
